# Generated by Django 4.2.7 on 2026-01-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notetemplate',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Теги для категоризации'),
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='template_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON структура шаблона с полями'),
        ),
        migrations.AlterField(
            model_name='notetemplate',
            name='content',
            field=models.TextField(blank=True, help_text='HTML содержимое шаблона'),
        ),
    ]
