# Generated by Django 4.2.7 on 2026-01-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notetemplate_options_notetemplate_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['-is_favorite', 'name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-usage_count', 'name']},
        ),
        migrations.AddField(
            model_name='folder',
            name='folder_type',
            field=models.CharField(choices=[('normal', 'Обычная папка'), ('smart', 'Умная папка'), ('favorite', 'Избранная папка')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Избранная папка для быстрого доступа'),
        ),
        migrations.AddField(
            model_name='folder',
            name='smart_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Правила для умной папки: теги, даты, типы'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_auto',
            field=models.BooleanField(default=False, help_text='Автоматически созданный тег'),
        ),
        migrations.AddField(
            model_name='tag',
            name='usage_count',
            field=models.IntegerField(default=0, help_text='Количество использований'),
        ),
    ]
