# Generated by Django 4.2.7 on 2026-01-08 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_folder_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='encryption_key_hash',
            field=models.CharField(blank=True, help_text='Хеш ключа шифрования', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Скрытая заметка'),
        ),
        migrations.AddField(
            model_name='note',
            name='visibility',
            field=models.CharField(choices=[('public', 'Публичная'), ('friends', 'Друзья'), ('private', 'Приватная')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Биография пользователя', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='following_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Публичный профиль'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='Местоположение', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, help_text='Веб-сайт', null=True),
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_notes', models.IntegerField(default=0)),
                ('total_characters', models.IntegerField(default=0)),
                ('total_words', models.IntegerField(default=0)),
                ('typing_speed_wpm', models.FloatField(default=0.0, help_text='Слов в минуту')),
                ('typing_speed_cpm', models.FloatField(default=0.0, help_text='Символов в минуту')),
                ('average_session_duration', models.DurationField(blank=True, null=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('streak_days', models.IntegerField(default=0, help_text='Текущий стрик')),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('fireflies_count', models.IntegerField(default=0, help_text='Количество "огоньков"')),
                ('rating_score', models.FloatField(default=0.0, help_text='Рейтинг активности')),
                ('level', models.IntegerField(default=1, help_text='Уровень пользователя')),
                ('experience_points', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статистика пользователя',
                'verbose_name_plural': 'Статистика пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0)),
                ('rank', models.IntegerField(default=0, help_text='Позиция в рейтинге')),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рейтинг пользователя',
                'verbose_name_plural': 'Рейтинги пользователей',
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='Отображаемое имя', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Биография')),
                ('location', models.CharField(blank=True, help_text='Местоположение', max_length=200)),
                ('website', models.URLField(blank=True, help_text='Веб-сайт')),
                ('avatar', models.FileField(blank=True, help_text='Аватар', null=True, upload_to='avatars/')),
                ('cover_image', models.FileField(blank=True, help_text='Обложка профиля', null=True, upload_to='covers/')),
                ('is_public', models.BooleanField(default=False, help_text='Публичный профиль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='TypingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('characters_typed', models.IntegerField(default=0)),
                ('words_typed', models.IntegerField(default=0)),
                ('typing_speed_wpm', models.FloatField(default=0.0)),
                ('typing_speed_cpm', models.FloatField(default=0.0)),
                ('errors_count', models.IntegerField(default=0)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typing_sessions', to='notes.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сессия печати',
                'verbose_name_plural': 'Сессии печати',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
