# Generated by Django 4.2.7 on 2026-01-08 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_encryption_key_hash_note_is_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='encryption_salt',
            field=models.TextField(blank=True, help_text='Salt для шифрования в base64', null=True),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_visibility', models.CharField(choices=[('public', 'Публичный'), ('friends', 'Только друзья'), ('private', 'Приватный')], default='public', help_text='Видимость профиля', max_length=20)),
                ('show_email', models.BooleanField(default=False, help_text='Показывать email')),
                ('show_statistics', models.BooleanField(default=True, help_text='Показывать статистику')),
                ('allow_follow_requests', models.BooleanField(default=True, help_text='Разрешить запросы на подписку')),
                ('default_note_visibility', models.CharField(choices=[('public', 'Публичная'), ('friends', 'Друзья'), ('private', 'Приватная')], default='private', help_text='Видимость заметок по умолчанию', max_length=20)),
                ('auto_save_enabled', models.BooleanField(default=True, help_text='Автосохранение заметок')),
                ('auto_save_interval', models.IntegerField(default=30, help_text='Интервал автосохранения в секундах')),
                ('email_notifications', models.BooleanField(default=False, help_text='Email уведомления')),
                ('push_notifications', models.BooleanField(default=True, help_text='Push уведомления')),
                ('notify_on_follow', models.BooleanField(default=True, help_text='Уведомлять о подписках')),
                ('notify_on_message', models.BooleanField(default=True, help_text='Уведомлять о сообщениях')),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Двухфакторная аутентификация')),
                ('session_timeout', models.IntegerField(default=7, help_text='Таймаут сессии в днях')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название для группового чата', max_length=200)),
                ('room_type', models.CharField(choices=[('direct', 'Личный чат'), ('group', 'Групповой чат')], default='direct', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_chat_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Чат-комната',
                'verbose_name_plural': 'Чат-комнаты',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Текст сообщения')),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('note', 'Заметка'), ('file', 'Файл'), ('image', 'Изображение')], default='text', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='chat_files/')),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='notes.note')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notes.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чата',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(blank=True, help_text='Время последнего прочитанного сообщения', null=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False, help_text='Администратор группы')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='notes.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник чата',
                'verbose_name_plural': 'Участники чата',
                'ordering': ['-joined_at'],
                'unique_together': {('room', 'user')},
            },
        ),
    ]
