# Generated by Django 4.2.7 on 2026-01-08 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_encryption_salt_usersettings_chatroom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Описание задания')),
                ('reward', models.IntegerField(default=0, help_text='Награда в валюте')),
                ('task_type', models.CharField(choices=[('daily', 'Ежедневное'), ('weekly', 'Еженедельное'), ('special', 'Специальное')], default='daily', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Задание активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['task_type', 'reward'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('template', 'Шаблон'), ('font', 'Шрифт'), ('animation', 'Анимация'), ('theme', 'Тема')], default='template', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('file', models.FileField(blank=True, help_text='Файл товара', null=True, upload_to='marketplace/')),
                ('preview_image', models.FileField(blank=True, help_text='Превью изображение', null=True, upload_to='marketplace/previews/')),
                ('description', models.TextField(help_text='Описание товара')),
                ('purchases_count', models.IntegerField(default=0, help_text='Количество покупок')),
                ('rating', models.FloatField(default=0.0, help_text='Рейтинг товара')),
                ('is_active', models.BooleanField(default=True, help_text='Товар активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Товар маркетплейса',
                'verbose_name_plural': 'Товары маркетплейса',
                'ordering': ['-rating', '-purchases_count', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Премиум шаблон'),
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Цена шаблона', max_digits=10),
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='purchases_count',
            field=models.IntegerField(default=0, help_text='Количество покупок'),
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='rating',
            field=models.FloatField(default=0.0, help_text='Рейтинг шаблона'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Сумма транзакции')),
                ('transaction_type', models.CharField(choices=[('earn', 'Заработано'), ('spend', 'Потрачено')], max_length=10)),
                ('description', models.TextField(help_text='Описание транзакции')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Firefly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Сообщение с "огоньком"', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fireflies', to='notes.note')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_fireflies', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_fireflies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Огонек',
                'verbose_name_plural': 'Огоньки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, help_text='Текущий баланс')),
                ('total_earned', models.IntegerField(default=0, help_text='Всего заработано')),
                ('total_spent', models.IntegerField(default=0, help_text='Всего потрачено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currency', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Валюта пользователя',
                'verbose_name_plural': 'Валюты пользователей',
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('reward_earned', models.IntegerField(default=0, help_text='Полученная награда')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='notes.dailytask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Выполнение задания',
                'verbose_name_plural': 'Выполнения заданий',
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'task')},
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='notes.marketplaceitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'ordering': ['-purchased_at'],
                'unique_together': {('user', 'item')},
            },
        ),
    ]
