# Generated by Django 4.2.7 on 2026-01-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_dailytask_marketplaceitem_notetemplate_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='attachment',
            field=models.FileField(blank=True, help_text='Прикрепленный файл', null=True, upload_to='note_attachments/'),
        ),
    ]
