# Generated by Django 4.2.7 on 2026-01-09 17:22

from django.db import migrations, models
import uuid


def generate_uuids_for_existing_records(apps, schema_editor):
    """Генерирует UUID для существующих записей"""
    models_to_update = [
        'User', 'UserProfile', 'Follow', 'Folder', 'Tag', 'NoteTemplate',
        'Note', 'UserStatistics', 'TypingSession', 'UserRating',
        'ChatRoom', 'ChatMember', 'ChatMessage', 'UserSettings',
        'MarketplaceItem', 'Purchase', 'Currency', 'DailyTask',
        'TaskCompletion', 'Transaction', 'Firefly'
    ]
    
    for model_name in models_to_update:
        try:
            Model = apps.get_model('notes', model_name)
            for obj in Model.objects.all():
                if not hasattr(obj, 'uuid') or obj.uuid is None:
                    obj.uuid = uuid.uuid4()
                    obj.save(update_fields=['uuid'])
        except Exception:
            # Игнорируем ошибки для моделей без записей
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_note_attachment'),
    ]

    operations = [
        # ШАГ 1: Добавляем поля БЕЗ unique (с null=True)
        migrations.AddField(
            model_name='chatmember',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='firefly',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='typingsession',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        
        # ШАГ 2: Генерируем UUID для существующих записей
        migrations.RunPython(generate_uuids_for_existing_records, migrations.RunPython.noop),
        
        # ШАГ 3: Делаем поля NOT NULL и UNIQUE
        migrations.AlterField(
            model_name='chatmember',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, help_text='Уникальный идентификатор участника'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, help_text='Уникальный идентификатор сообщения'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, help_text='Уникальный идентификатор чат-комнаты'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, help_text='Уникальный идентификатор валюты'),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, help_text='Уникальный идентификатор задания'),
        ),
        migrations.AlterField(
            model_name='firefly',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, help_text='Уникальный идентификатор огонька'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, help_text='Уникальный идентификатор папки'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, help_text='Уникальный идентификатор подписки'),
        ),
        migrations.AlterField(
            model_name='marketplaceitem',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, help_text='Уникальный идентификатор товара'),
        ),
        migrations.AlterField(
            model_name='note',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, help_text='Уникальный идентификатор заметки'),
        ),
        migrations.AlterField(
            model_name='notetemplate',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, help_text='Уникальный идентификатор шаблона'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, help_text='Уникальный идентификатор покупки'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, help_text='Уникальный идентификатор тега'),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, help_text='Уникальный идентификатор выполнения'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, help_text='Уникальный идентификатор транзакции'),
        ),
        migrations.AlterField(
            model_name='typingsession',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, help_text='Уникальный идентификатор сессии'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, help_text='Уникальный идентификатор пользователя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, help_text='Уникальный идентификатор профиля'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, help_text='Уникальный идентификатор рейтинга'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, help_text='Уникальный идентификатор настроек'),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, help_text='Уникальный идентификатор статистики'),
        ),
    ]
