# Generated by Django 4.2.7 on 2026-01-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_chatmember_uuid_chatmessage_uuid_chatroom_uuid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmember',
            options={'ordering': ['-is_favorite', '-joined_at'], 'verbose_name': 'Участник чата', 'verbose_name_plural': 'Участники чата'},
        ),
        migrations.AddField(
            model_name='chatmember',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Избранный чат'),
        ),
    ]
